name: Test Building Vitepress Website

on:
  push:
  pull_request:
  workflow_dispatch:

  repository_dispatch:
    types: [trigger-from-chai]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Vitepress
        run: |
          git clone https://github.com/nios-students/nios-web website

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: "website/docs/temp"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: "website/package-lock.json"
          cache: npm

      - name: Install dependencies
        run: cd website; npm ci

      - name: Build with VitePress
        run: |
          cd website/docs
          wget https://raw.githubusercontent.com/nios-students/helper_scripts/refs/heads/fix/build.sh
          bash build.sh SKIP_DOCS

      - name: Upload artifact
        # ✅ UPDATED CONDITION
        if: |
          github.ref == 'refs/heads/contents' &&
          (
            github.event_name == 'push' ||
            github.event_name == 'workflow_dispatch' ||
            github.event_name == 'repository_dispatch'
          )

        uses: actions/upload-pages-artifact@v3
        with:
          path: website/docs/.vitepress/dist

  deploy:
    # ✅ UPDATED CONDITION
    if: |
      github.ref == 'refs/heads/contents' &&
      (
        github.event_name == 'push' ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'repository_dispatch'
      )

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
